language: node_js
node_js:
  - "lts/carbon"
  - "lts/10.13.0"
  - "lts/10.15.0"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'
services:
  - docker
  - mongodb
sudo: required
before_install:
  - export TZ=Africa/Johannesburg
after_success:
  - npm run coverage
  - ".travis/build_docker.sh"
notifications:
  slack:
    rooms:
      - jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
    on_success: change
    on_failure: always
